<?php
/**
 * Setup theme
 */
function ghe_theme_setup() {

	register_nav_menus(
		array(
			'main-menu'      => __( 'Main Menu', 'grand-hotel-europe' ),
			'mega-menu'      => __( 'Mega Menu', 'grand-hotel-europe' ),
			'footer-menu-1'   => __( 'Footer Menu 1', 'grand-hotel-europe' ),
			'footer-menu-2'   => __( 'Footer Menu 2', 'grand-hotel-europe' ),
			'copyright-menu' => __( 'Copyright Menu', 'grand-hotel-europe' ),
		)
	);

	add_theme_support( 'menus' );

	add_theme_support( 'custom-logo' );

	add_theme_support( 'title-tag' );

	add_theme_support( 'post-thumbnails' );

	add_theme_support( 'html5', array( 'comment-list', 'comment-form', 'search-form', 'gallery', 'caption', 'style', 'script' ) );

	add_image_size( 'zimmer-suiten-gallery', 1280, 689, array( 'center', 'center' ) );
 
}

add_action( 'after_setup_theme', 'ghe_theme_setup' );
/**  
 * Register our sidebars and widgetized areas.
 */
function ghe_theme_footer_widgets_init() {

	register_sidebar(
		array(
			'name'          => 'Footer',
			'id'            => 'footer',
			'before_widget' => '<div id="%1$s" class="widget %2$s">',
			'after_widget'  => '</div>',
			'before_title'  => '<h3 class="widget-title">',
			'after_title'   => '</h3>',
		),
	);

	register_sidebar(
		array(
			'name'          => 'Mega Menu Language Switcher',
			'id'            => 'megamenu_ls',
			'before_widget' => '<div id="%1$s" class="%2$s">',
			'after_widget'  => '</div>',
			'before_title'  => '',
			'after_title'   => '',
		)
	);

}

add_action( 'widgets_init', 'ghe_theme_footer_widgets_init' );

/**
 * Load external font stylesheets asynchronously to avoid render-blocking.
 *
 * Intercepts the default <link rel="stylesheet"> tags generated by WordPress
 * for font handles and replaces them with a non-blocking preload pattern.
 * Uses the $href provided by WordPress so the URL is never hardcoded twice.
 * The preconnect hints are handled separately via ghe_resource_hints().
 *
 * @param string $html   The full <link> tag HTML generated by WordPress.
 * @param string $handle The registered style handle.
 * @param string $href   The stylesheet URL.
 * @param string $media  The stylesheet media attribute.
 * @return string
 */
function ghe_fonts_non_blocking_loader( string $html, string $handle, string $href, string $media ): string {
	$async_handles = array( 'typekit-fonts', 'google-fonts' );

	if ( ! in_array( $handle, $async_handles, true ) ) {
		return $html;
	}

	$media_attr = $media && 'all' !== $media
		? ' media="' . esc_attr( $media ) . '"'
		: '';

	return '<link rel="preload" href="' . esc_url( $href ) . '" as="style" crossorigin="anonymous" onload="this.onload=null;this.rel=\'stylesheet\'"' . $media_attr . '>' . "\n"
		. '<noscript><link rel="stylesheet" href="' . esc_url( $href ) . '"' . $media_attr . '></noscript>' . "\n";
}
add_filter( 'style_loader_tag', 'ghe_fonts_non_blocking_loader', 10, 4 );

/**
 * Add preconnect and DNS-prefetch resource hints for external origins.
 *
 * @param array  $hints         URLs to print for resource hints.
 * @param string $relation_type The relation type (preconnect, dns-prefetch, etc.).
 * @return array
 */
function ghe_resource_hints( array $hints, string $relation_type ): array {
	if ( 'preconnect' === $relation_type ) {
		$hints[] = array(
			'href'        => 'https://use.typekit.net',
			'crossorigin' => 'anonymous',
		);
		$hints[] = array(
			'href'        => 'https://fonts.googleapis.com',
			'crossorigin' => 'anonymous',
		);
		$hints[] = array(
			'href'        => 'https://fonts.gstatic.com',
			'crossorigin' => 'anonymous',
		);
	}

	if ( 'dns-prefetch' === $relation_type ) {
		$hints[] = array( 'href' => 'https://www.google-analytics.com' );
	}

	return $hints;
}
add_filter( 'wp_resource_hints', 'ghe_resource_hints', 10, 2 );


/**
 * Enqueue styles and scripts
 */
function ghe_theme_enqueue_styles() {

	//Get the theme data
	$the_theme     = wp_get_theme();
	$theme_version = $the_theme->get( 'Version' );

	// Font stylesheets (non-blocking via style_loader_tag filters).
	wp_enqueue_style( 'typekit-fonts', 'https://use.typekit.net/ykk6hgi.css', array(), null );
	wp_enqueue_style( 'google-fonts', 'https://fonts.googleapis.com/css2?family=Gilda+Display&display=swap', array(), null );

	// Register Theme main style (depends on fonts so they load first).
	wp_enqueue_style( 'theme-styles', get_template_directory_uri() . '/dist/css/main.css', array( 'typekit-fonts', 'google-fonts' ), $theme_version );

	wp_enqueue_script( 'jquery', false, array(), $theme_version, true );
	wp_enqueue_script( 'theme-scripts', get_stylesheet_directory_uri() . '/dist/js/main.js', array( 'jquery' ), $theme_version, true );

	if ( is_page_template( 'page-templates/page-arrival-contact.php' ) || is_admin() ) :
				wp_enqueue_script( 'google-map-settings', get_stylesheet_directory_uri() . '/assets/js/google-maps.js', array( 'jquery' ), $theme_version, true );
				wp_enqueue_script( 'google-map-api', 'https://maps.googleapis.com/maps/api/js?key=AIzaSyBAZN5TfX1aWmjodZ4e_6sOcaJV4D59jfo&callback=initMap&loading=async', array(), $theme_version, true );
	endif; 
}

add_action( 'wp_enqueue_scripts', 'ghe_theme_enqueue_styles' );


/**
 * Initialize Google Map API key for ACF in admin.
 */

function ghe_google_map_init() {
		if ( is_admin() ) :
				acf_update_setting( 'google_api_key', 'AIzaSyBAZN5TfX1aWmjodZ4e_6sOcaJV4D59jfo' );
		endif;
}

add_action( 'acf/init', 'ghe_google_map_init' );

/**
 * Remove <p> Tag From Contact Form 7.
 */
add_filter( 'wpcf7_autop_or_not', '__return_false' );

/**
 * Lowers the metabox priority to 'core' for Yoast SEO's metabox.
 *
 * @param string $priority The current priority.
 *
 * @return string $priority The potentially altered priority.
 */
function ghe_theme_lower_yoast_metabox_priority( $priority ) {
	return 'core';
}


// Remove reCAPTCHA scripts do CF7 globalmente.
add_filter( 'wpcf7_load_js', '__return_false' );
add_filter( 'wpcf7_load_css', '__return_false' );

// Carrega só nas páginas que têm formulário.
add_action(
	'wp_enqueue_scripts',
	function () {
		if ( is_page_template( 'page-templates/page-arrival-contact.php' ) ) {
			wpcf7_enqueue_scripts();
			wpcf7_enqueue_styles();
		}
	}
);

/**
 * CF7: Add current page context (title + url) as hidden fields.
 * Works even when the form is rendered via do_shortcode() in templates.
 */
add_filter( 'wpcf7_form_hidden_fields', function ( $hidden_fields ) {
	$post_id = get_queried_object_id();

	// Helps CF7 post-related tags when possible (singular pages).
	if ( $post_id ) {
		$hidden_fields['_wpcf7_container_post'] = (string) $post_id;
	}

	// Title: use real post title when singular, otherwise fallback to document title (archives, etc.).
	$title = ( is_singular() && $post_id ) ? get_the_title( $post_id ) : wp_get_document_title();

	// URL: current URL (includes query string when present).
	$current_url = home_url( add_query_arg( null, null ) );

	$hidden_fields['geh_page_title'] = wp_strip_all_tags( (string) $title );
	$hidden_fields['geh_page_url']   = esc_url_raw( $current_url );

	return $hidden_fields;
}, 10, 1 );

add_filter( 'wpseo_metabox_prio', 'ghe_theme_lower_yoast_metabox_priority' );


//Simple booking integration
add_action('wp', function () {
	if (is_front_page()) {
		require_once get_template_directory() . '/inc/theme-simple-booking.php';
	}
});

// Custom Breadcrumbs for the Zimmer & Suiten
require get_template_directory() . '/inc/theme-custom-breadcrumbs.php';

// Theme custom template tags.
require get_template_directory() . '/inc/theme-template-tags.php';

// The theme admin settings.
require get_template_directory() . '/inc/theme-admin-settings.php';

// The theme custom menu walker settings.
require get_template_directory() . '/inc/theme-custom-menu-walker.php';

function my_console_log(...$data) {
	$json = json_encode($data);
	add_action('shutdown', function() use ($json) {
		 echo "<script>console.log({$json})</script>";
	});
}

